<?php
/**
 * Implements hook_classier_paragraphs_form().
 */
function responsive_paragraphs_classier_paragraphs_form($entity_type, $bundle, $item) {
  $element['responsive'] = [
    '#type' => 'details',
    '#open' => FALSE,
    '#title' => t('Responsive visibility'),
    '#description' => t('Sets content visibility based on bootstrap breakpoints.'),
    'responsive_options_up' => [
      '#type' => 'radios',
      '#title' => t('.hidden-*-down'),
      '#options' => [
        '' => t('None'),
        'd-none d-sm-block' => t('Hidden below 575 px.'),
        'd-none d-md-block' => t('Hidden below 768 px.'),
        'd-none d-lg-block' => t('Hidden below 992 px.'),
        'd-none d-xl-block' => t('Hidden below 1200 px.'),
      ],
      '#default_value' => isset($item->responsive['responsive_options_up']) ? $item->responsive['responsive_options_up'] : '',
    ],
    'responsive_options_down' => [
      '#type' => 'radios',
      '#title' => t('.hidden-*-up'),
      '#options' => [
        '' => t('None'),
        'd-sm-none' => t('Hidden above 575 px.'),
        'd-md-none' => t('Hidden above 767 px.'),
        'd-lg-none' => t('Hidden above 991 px.'),
        'd-xl-none' => t('Hidden above 1199 px.'),
      ],
      '#default_value' => isset($item->responsive['responsive_options_down']) ? $item->responsive['responsive_options_down'] : '',
    ],
  ];
  return $element;
}
